name: roseapple-pi 
vendor: Woodrow Shen <woodrow.shen@canonical.com>
icon: meta/roseapple-pi.png
version: 0.1
type: oem

config:
  ubuntu-core:
    hostname: roseapple-pi   
    services:
        - name: ssh
          enabled: true
    autopilot: false

oem:
  branding:
    name: Roseapple Pi
    logo: meta/roseapple-pi.png
  software:
    preinstalled:
        - webdm
  hardware:
    platform: actduino_bubble_gum_sdboot_linux
    architecture: armhf
    partition-layout: system-AB
    bootloader: u-boot
    boot-assets:
      files:
        - path: boot-assets/uEnv.txt
        - path: boot-assets/boot.scr
      raw-files:
        - path: boot-assets/bootloader.bin
          offset: 2097664 #4097*512
        - path: boot-assets/u-boot.bin
          offset: 3145728 #6144*512
